name: pyright

on:
  push:
    branches: [main]
  pull_request:

jobs:
  type-check:
    runs-on: ubuntu-latest

    name: type-check

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install-uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
        with:
          enable-cache: true

      - name: venv
        run: uv venv && uv sync --all-extras

      - name: pyright
        run: uv run pyright tinker_cookbook
